### PR TITLE
GPII-2380: Update to "root safe dedupe" version of infusion...

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-2380](https://issues.gpii.net/browse/GPII-2380) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
I am opening this to remind myself that it is in flight, but this is not currently ready for review.  The screenshot tests consistently timeout.

**Comment by amb26** [comment]
This failed for me with the following results:

```
13:40:16.565:  FATAL ERROR: Uncaught exception: Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (E:\source\gits\gpii-webdriver\node_modules\istanbul\lib\
hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\source\gits\gpii-webdriver\src\js\webdriver.js:9:280)
    at Module._compile (module.js:409:26)
=============================================================================
Writing coverage object [E:\source\gits\gpii-webdriver\coverage\coverage.json]
Writing coverage reports at [E:\source\gits\gpii-webdriver\coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 23.61% ( 17/72 ), 10 ignored
Branches     : 33.33% ( 2/6 ), 2 ignored
Functions    : 25% ( 3/12 ), 3 ignored
Lines        : 23.61% ( 17/72 )
================================================================================
```

**Comment by amb26** [comment]
Ignore this, looks like it was caused by using the node 4.5.x which I currently have on my laptop

**Comment by amb26** [comment]
With the proper dependencies installed, I still get one test failure:
```
14:08:31.428:  jq: FAIL: Module "Testing static URL resolution function..." Test name "Package-relative paths should be
resolved" - Message: A package-relative path should be resolved correctly...
14:08:31.438:  jq: Expected: file:///E://source/gits/gpii-webdriver/tests/js/resolve-file-url.js
14:08:31.443:  jq: Actual: file:///E:/source/gits/gpii-webdriver/tests/js/resolve-file-url.js
14:08:31.449:  jq: Source:     at Object.assertEquals (E:\source\gits\gpii-webdriver\node_modules\infusion\tests\test-co
re\jqUnit\js\jqUnit.js:137:19)
    at Object.<anonymous> (E:\source\gits\gpii-webdriver\tests\js\resolve-file-url.js:24:12)
    at Object.run (E:\source\gits\gpii-webdriver\node_modules\infusion\tests\lib\qunit\js\qunit.js:207:18)
    at E:\source\gits\gpii-webdriver\node_modules\infusion\tests\lib\qunit\js\qunit.js:365:10
    at process (E:\source\gits\gpii-webdriver\node_modules\infusion\tests\lib\qunit\js\qunit.js:1457:24)
    at Timeout._onTimeout (E:\source\gits\gpii-webdriver\node_modules\infusion\tests\lib\qunit\js\qunit.js:483:5)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
```

**Comment by the-t-in-rtf** [comment]
Looks like I need different handling for the path resolution for Windows 7 and Windows 10.  Will investigate on the morrow.

**Comment by the-t-in-rtf** [comment]
@amb26, I have simplified the test logic used in verifying that file paths are resolved correctly, and confirmed that it works on both the Windows 7 and Windows 10 VMs as well as OS X.  Please pull the latest commits and confirm if this fixes the broken test on your machine.

**Comment by the-t-in-rtf** [comment]
@amb26, as we already have a "root safe dedupe" release of gpii-pouchdb, this is now the sticking point in pushing further through the stack.

**Comment by amb26** [comment]
Sadly with these updates I still get just the same failure in constructing file URLs:

```
20:32:31.801:  jq: FAIL: Module "Testing static URL resolution function..." Test name "Package-relative paths should be resolved" - Message: A package-relative
path should be resolved correctly...
20:32:31.802:  jq: Expected: file:///E://source/gits/gpii-webdriver/tests/js/resolve-file-url.js
20:32:31.804:  jq: Actual: file:///E:/source/gits/gpii-webdriver/tests/js/resolve-file-url.js
20:32:31.807:  jq: Source:     at Object.assertEquals (E:\source\gits\gpii-webdriver\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:137:19)
```

In addition, the very final test of the set hangs after trying to take the screenshot - the browser window is left open:
```
20:33:59.252:  Test case listener has not responded after 5000ms - at sequence pos 5 of 7 sequence element {
    "event": "{testEnvironment}.webdriver.events.onTakeScreenshotComplete",
    "listener": "gpii.tests.webdriver.takeScreenshot.examineResults",
    "args": [
        "{arguments}.0"
    ]
} of fixture chrome: Take a screenshot and examine the results...
=============================================================================
Writing coverage object [E:\source\gits\gpii-webdriver\coverage\coverage.json]
Writing coverage reports at [E:\source\gits\gpii-webdriver\coverage]
=============================================================================
```

Oddly the test run seems to conclude, but I do not get the expected PASS/FAIL summary at the end, only the coverage summary.

**Comment by the-t-in-rtf** [comment]
Looks like my function that generates a path for comparison is only safe when run from the root of a drive, I can trivially reproduce by checking the code out in a deeper directory.  Will harden further shortly.

For the webdriver errors, I cannot reproduce the problem you're seeing in the Windows 10 VM with Chrome 57.0.2987.133 and Chromedriver 2.29.461591

@amb26, What versions of Chrome/chromedriver do you have?

**Comment by the-t-in-rtf** [comment]
@amb26, the file URL test failure was down to the current behavior of `fluid.module.resolvePath`, which I wrote up in [FLUID-6155](https://issues.fluidproject.org/browse/FLUID-6155).  I added a workaround which works both in the root of a drive (as I use with vagrant) and in a deep path (where you encountered the problem).

**Pull request merged**
